name: Publish documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate documentation
      run: >
        swift package --allow-writing-to-directory './Documentation'
        generate-documentation
        --disable-indexing
        --transform-for-static-hosting
        --hosting-base-path "${GITHUB_REPOSITORY#*/}"
        --output-path './Documentation'
    - name: Setup Pages
      uses: actions/configure-pages@v1
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './Documentation'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
